# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import execution_engine_pb2 as eventflow_dot_execution__engine__pb2

GRPC_GENERATED_VERSION = "1.82.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in eventflow/execution_engine_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ExecutionEngineServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartExecution = channel.unary_unary(
            "/eventflow.ExecutionEngineService/StartExecution",
            request_serializer=eventflow_dot_execution__engine__pb2.StartExecutionRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.ExecutionDTO.FromString,
            _registered_method=True,
        )
        self.GetExecution = channel.unary_unary(
            "/eventflow.ExecutionEngineService/GetExecution",
            request_serializer=eventflow_dot_execution__engine__pb2.GetExecutionRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.ExecutionDTO.FromString,
            _registered_method=True,
        )
        self.GetNodeExecutions = channel.unary_unary(
            "/eventflow.ExecutionEngineService/GetNodeExecutions",
            request_serializer=eventflow_dot_execution__engine__pb2.GetNodeExecutionsRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.NodeExecutionListDTO.FromString,
            _registered_method=True,
        )
        self.ListExecutions = channel.unary_unary(
            "/eventflow.ExecutionEngineService/ListExecutions",
            request_serializer=eventflow_dot_execution__engine__pb2.ListExecutionsRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.ExecutionListDTO.FromString,
            _registered_method=True,
        )
        self.TransitionNode = channel.unary_unary(
            "/eventflow.ExecutionEngineService/TransitionNode",
            request_serializer=eventflow_dot_execution__engine__pb2.TransitionNodeRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.NodeExecutionDTO.FromString,
            _registered_method=True,
        )
        self.RetryNode = channel.unary_unary(
            "/eventflow.ExecutionEngineService/RetryNode",
            request_serializer=eventflow_dot_execution__engine__pb2.RetryNodeRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.NodeExecutionDTO.FromString,
            _registered_method=True,
        )
        self.DeleteExecution = channel.unary_unary(
            "/eventflow.ExecutionEngineService/DeleteExecution",
            request_serializer=eventflow_dot_execution__engine__pb2.DeleteExecutionRequest.SerializeToString,
            response_deserializer=eventflow_dot_execution__engine__pb2.DeleteExecutionResponse.FromString,
            _registered_method=True,
        )


class ExecutionEngineServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNodeExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TransitionNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RetryNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExecutionEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartExecution": grpc.unary_unary_rpc_method_handler(
            servicer.StartExecution,
            request_deserializer=eventflow_dot_execution__engine__pb2.StartExecutionRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.ExecutionDTO.SerializeToString,
        ),
        "GetExecution": grpc.unary_unary_rpc_method_handler(
            servicer.GetExecution,
            request_deserializer=eventflow_dot_execution__engine__pb2.GetExecutionRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.ExecutionDTO.SerializeToString,
        ),
        "GetNodeExecutions": grpc.unary_unary_rpc_method_handler(
            servicer.GetNodeExecutions,
            request_deserializer=eventflow_dot_execution__engine__pb2.GetNodeExecutionsRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.NodeExecutionListDTO.SerializeToString,
        ),
        "ListExecutions": grpc.unary_unary_rpc_method_handler(
            servicer.ListExecutions,
            request_deserializer=eventflow_dot_execution__engine__pb2.ListExecutionsRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.ExecutionListDTO.SerializeToString,
        ),
        "TransitionNode": grpc.unary_unary_rpc_method_handler(
            servicer.TransitionNode,
            request_deserializer=eventflow_dot_execution__engine__pb2.TransitionNodeRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.NodeExecutionDTO.SerializeToString,
        ),
        "RetryNode": grpc.unary_unary_rpc_method_handler(
            servicer.RetryNode,
            request_deserializer=eventflow_dot_execution__engine__pb2.RetryNodeRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.NodeExecutionDTO.SerializeToString,
        ),
        "DeleteExecution": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteExecution,
            request_deserializer=eventflow_dot_execution__engine__pb2.DeleteExecutionRequest.FromString,
            response_serializer=eventflow_dot_execution__engine__pb2.DeleteExecutionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "eventflow.ExecutionEngineService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("eventflow.ExecutionEngineService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ExecutionEngineService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartExecution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/StartExecution",
            eventflow_dot_execution__engine__pb2.StartExecutionRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.ExecutionDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetExecution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/GetExecution",
            eventflow_dot_execution__engine__pb2.GetExecutionRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.ExecutionDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNodeExecutions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/GetNodeExecutions",
            eventflow_dot_execution__engine__pb2.GetNodeExecutionsRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.NodeExecutionListDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListExecutions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/ListExecutions",
            eventflow_dot_execution__engine__pb2.ListExecutionsRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.ExecutionListDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TransitionNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/TransitionNode",
            eventflow_dot_execution__engine__pb2.TransitionNodeRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.NodeExecutionDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RetryNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/RetryNode",
            eventflow_dot_execution__engine__pb2.RetryNodeRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.NodeExecutionDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteExecution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventflow.ExecutionEngineService/DeleteExecution",
            eventflow_dot_execution__engine__pb2.DeleteExecutionRequest.SerializeToString,
            eventflow_dot_execution__engine__pb2.DeleteExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
