# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eventflow/worker_control.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 0, "", "eventflow/worker_control.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x65ventflow/worker_control.proto\x12\teventflow"k\n\x16WorkerHeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1b\n\x0e\x63urrent_job_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_current_job_id"*\n\x17WorkerHeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"D\n\x14\x43laimStaleJobRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x19\n\x11node_execution_id\x18\x02 \x01(\t"(\n\x15\x43laimStaleJobResponse\x12\x0f\n\x07\x63laimed\x18\x01 \x01(\x08\x32\xc4\x01\n\x14WorkerControlService\x12X\n\x0fReportHeartbeat\x12!.eventflow.WorkerHeartbeatRequest\x1a".eventflow.WorkerHeartbeatResponse\x12R\n\rClaimStaleJob\x12\x1f.eventflow.ClaimStaleJobRequest\x1a .eventflow.ClaimStaleJobResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "eventflow.worker_control_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WORKERHEARTBEATREQUEST"]._serialized_start = 45
    _globals["_WORKERHEARTBEATREQUEST"]._serialized_end = 152
    _globals["_WORKERHEARTBEATRESPONSE"]._serialized_start = 154
    _globals["_WORKERHEARTBEATRESPONSE"]._serialized_end = 196
    _globals["_CLAIMSTALEJOBREQUEST"]._serialized_start = 198
    _globals["_CLAIMSTALEJOBREQUEST"]._serialized_end = 266
    _globals["_CLAIMSTALEJOBRESPONSE"]._serialized_start = 268
    _globals["_CLAIMSTALEJOBRESPONSE"]._serialized_end = 308
    _globals["_WORKERCONTROLSERVICE"]._serialized_start = 311
    _globals["_WORKERCONTROLSERVICE"]._serialized_end = 507
# @@protoc_insertion_point(module_scope)
