# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eventflow import worker_control_pb2 as eventflow_dot_worker__control__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eventflow/worker_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportHeartbeat = channel.unary_unary(
                '/eventflow.WorkerControlService/ReportHeartbeat',
                request_serializer=eventflow_dot_worker__control__pb2.WorkerHeartbeatRequest.SerializeToString,
                response_deserializer=eventflow_dot_worker__control__pb2.WorkerHeartbeatResponse.FromString,
                _registered_method=True)
        self.ClaimStaleJob = channel.unary_unary(
                '/eventflow.WorkerControlService/ClaimStaleJob',
                request_serializer=eventflow_dot_worker__control__pb2.ClaimStaleJobRequest.SerializeToString,
                response_deserializer=eventflow_dot_worker__control__pb2.ClaimStaleJobResponse.FromString,
                _registered_method=True)


class WorkerControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimStaleJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHeartbeat,
                    request_deserializer=eventflow_dot_worker__control__pb2.WorkerHeartbeatRequest.FromString,
                    response_serializer=eventflow_dot_worker__control__pb2.WorkerHeartbeatResponse.SerializeToString,
            ),
            'ClaimStaleJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimStaleJob,
                    request_deserializer=eventflow_dot_worker__control__pb2.ClaimStaleJobRequest.FromString,
                    response_serializer=eventflow_dot_worker__control__pb2.ClaimStaleJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventflow.WorkerControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eventflow.WorkerControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventflow.WorkerControlService/ReportHeartbeat',
            eventflow_dot_worker__control__pb2.WorkerHeartbeatRequest.SerializeToString,
            eventflow_dot_worker__control__pb2.WorkerHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimStaleJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventflow.WorkerControlService/ClaimStaleJob',
            eventflow_dot_worker__control__pb2.ClaimStaleJobRequest.SerializeToString,
            eventflow_dot_worker__control__pb2.ClaimStaleJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
