"""initial schema

Revision ID: 87925a676c08
Revises: 
Create Date: 2026-07-13 12:15:10.609977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87925a676c08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('workers',
    sa.Column('worker_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'STALE', name='worker_status', native_enum=False, length=32), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_job_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_name')
    )
    op.create_index('ix_workers_last_heartbeat_at', 'workers', ['last_heartbeat_at'], unique=False)
    op.create_table('workflows',
    sa.Column('owner_api_key_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_versions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version_number')
    )
    op.create_table('executions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PARTIAL_FAILED', 'CANCELLED', name='execution_status', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_status', 'executions', ['status'], unique=False)
    op.create_index('ix_executions_workflow_version_id', 'executions', ['workflow_version_id'], unique=False)
    op.create_table('node_executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'SKIPPED', 'DEAD_LETTERED', name='node_execution_status', native_enum=False, length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('redis_message_id', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'node_id')
    )
    op.create_index('ix_node_executions_execution_id_status', 'node_executions', ['execution_id', 'status'], unique=False)
    op.create_index('ix_node_executions_idempotency_key', 'node_executions', ['idempotency_key'], unique=False)
    op.create_table('dead_letter_jobs',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_execution_id', sa.UUID(), nullable=False),
    sa.Column('redis_message_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['node_execution_id'], ['node_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dead_letter_jobs_resolved_at', 'dead_letter_jobs', ['resolved_at'], unique=False)
    op.create_table('execution_logs',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_execution_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level', native_enum=False, length=16), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['node_execution_id'], ['node_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_logs_execution_id_created_at', 'execution_logs', ['execution_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_logs_execution_id_created_at', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_dead_letter_jobs_resolved_at', table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    op.drop_index('ix_node_executions_idempotency_key', table_name='node_executions')
    op.drop_index('ix_node_executions_execution_id_status', table_name='node_executions')
    op.drop_table('node_executions')
    op.drop_index('ix_executions_workflow_version_id', table_name='executions')
    op.drop_index('ix_executions_status', table_name='executions')
    op.drop_table('executions')
    op.drop_table('workflow_versions')
    op.drop_table('workflows')
    op.drop_index('ix_workers_last_heartbeat_at', table_name='workers')
    op.drop_table('workers')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
